import ReduxProvider from '@/redux/provider'
import Main from '@/Component/Main';
import { Inter } from 'next/font/google'
import "../assets/plugins/nucleo/css/nucleo.css";
import "../assets/css/custom.css";
import './globals.css'
import "../assets/css/dashboard-react.css"
import "../assets/scss/custom-theme/main.scss";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Main>{children}</Main>
        </ReduxProvider>
      </body>
    </html>
  )
}
